### PR TITLE
#157768696 Add make_request page

### PR DESCRIPTION
**Pull request by PaulKitonyi**
### What does this PR do?

- Adds a make_request page.

### Description of task completed?

- Create a page where user can make a request.

### How should this be manually tested?
- Clone or download the project
```$ git clone https://github.com/paulkitonyi/Maintenance-Tracker/tree/ft-make-requests-page-157768696```
- Navigate to UI/ directory, then click the make_request.html file to view the make request page on a browser.

### Any background context you want to provide?
- Created using: HTML5 and CSS

### What are the relevant pivotal tracker stories?
[#157768696](https://www.pivotaltracker.com/n/projects/2173306/stories/157768696)

### Screenshots (if appropriate)
screenshot from 2018-05-25 12-59-36

### CODE REVIEW

**Comment by dessHub** [comment]
Work on your commit message.

**Comment by maxwellgithinji** [comment]
UI looks good, but you should work on your commit messages. Here is a link https://github.com/andela/bestpractices/wiki/Git-naming-conventions-and-best-practices

**Comment by PaulKitonyi** [comment]
Thanks for the review and feedback.Now i see.

**Comment by PaulKitonyi** [comment]
Thanks for the review and feedback.Now i see.

**Comment by Slinjez** [comment]
pr well done

**Comment by alovega** [comment]
to me request page awesome  I really like it

**Comment by PaulKitonyi** [comment]
Thanks.

**Pull request merged**
