### PR TITLE
 #157768910 Add admin_dashboard page

### PR DESCRIPTION
**Pull request by PaulKitonyi**
### What does this PR do?
- Adds an admin dashboard page.

### Description of task completed?
- Create a page where an admin can manage the application from.

### How should this be manually tested?
- Clone or download the project
$ git clone https://github.com/paulkitonyi/Maintenance-Tracker/tree/ft-admin-dashboard-page-#157768910
- Navigate to UI directory then admin, and click the admin_dashboard.html file to view the admin dashboard page on a browser.

### Any background context you want to provide?
Created using: HTML5 and CSS.Not yet Responsive.

### What are the relevant pivotal tracker stories?
[##157768910](https://www.pivotaltracker.com/n/projects/2173306/stories/157768910)

### Screenshots (if appropriate)
screenshot from 2018-05-26 16-54-32

### CODE REVIEW

**Comment by gtsofa** [comment]
Very simple UI. Good PR

**Comment by PaulKitonyi** [comment]
Thanks for the review.

**Comment by Slinjez** [comment]
good UI, nicely done pr, I hope the dashboard won't remain blank

**Comment by PaulKitonyi** [comment]
🤗 NO

**Pull request merged**
