### PR TITLE
 #157768483 Add user signup page

### PR DESCRIPTION
**Pull request by PaulKitonyi**
#### What does this PR do?
- Creates user sign up page.

#### Description of Task to be completed?
- Have a  form where new user can create account.

#### How should this be manually tested?
- Clone this repo and cd to UI folder  then open ```signup.html ```file.

#### Any background context you want to provide?
None.

#### What are the relevant pivotal tracker stories?
[#157768483](https://www.pivotaltracker.com/n/projects/2173306/stories/157768483)

#### Screenshots (if appropriate)
screenshot from 2018-05-24 11-44-38

### CODE REVIEW

**Comment by gitaumoses4** [comment]
This is great. Branches are well named, descriptive and consistent.

**Comment by gitaumoses4** [comment]
You may also have to change the commit messages:
## Example
`updated index.html` should be `Update index.html`

Checkout this [article](https://chris.beams.io/posts/git-commit/)

**Comment by johnmusiu** [comment]
PR look great. 
UI is cool
Add link to PT story at the PT stories section

**Comment by mmosoroohh** [comment]
PR is very descriptive
UI Design looks great

**Comment by PaulKitonyi** [comment]
Thanks

**Comment by gtsofa** [comment]
Nice PR!!. A small fix though, can you make the **sign up** button look a bit nice and consistent  :-)

**Comment by PaulKitonyi** [comment]
Alright.On it.Thanks.

**Pull request merged**
