### PR TITLE
#157876871 Add edit account page

### PR DESCRIPTION
**Pull request by PaulKitonyi**
### What does this PR do?
- Adds an edit account page.

### Description of task completed?
- Create a page where an admin and user can edit their accounts.

### How should this be manually tested?
- Clone or download the project
$ git clone https://github.com/paulkitonyi/Maintenance-Tracker/tree/ft-edit-account-page-##157876871
- Navigate to UI directory, and click the edit_account.html file to view the page which will be fetching account data for edit on a browser.

### Any background context you want to provide?
- Created using: HTML5 and CSS.Not yet Responsive.

### What are the relevant pivotal tracker stories?
[#157876871](https://www.pivotaltracker.com/n/projects/2173306/stories/157876871)

### Screenshots (if appropriate)
screenshot from 2018-05-26 18-51-36

### CODE REVIEW

**Comment by lawrenceChege** [comment]
the ui is good.
the commits and pr are well structured

**Comment by Slinjez** [comment]
Nice pr structure... cool UI man

**Comment by PaulKitonyi** [comment]
Thanks for review.

**Comment by PaulKitonyi** [comment]
Thanks for review and feedback.

**Pull request merged**
